// services/exercises/seed.ts
// Optional seed: generated by tools/make-seed.ts -> assets/exercises.seed.json
// If you haven't generated it yet, you can keep this file and just return [].

import type { ExerciseDoc } from "./types";

// If your repo already contains this file, keep it.
// If not, either generate it OR temporarily set SEED = [].
let SEED: ExerciseDoc[] = [];
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  SEED = require("@/assets/exercises.seed.json");
} catch {
  SEED = [];
}

export const EXERCISE_SEED: ExerciseDoc[] = Array.isArray(SEED) ? SEED : [];
