// services/badges/registry.ts
import type { BadgeDef } from "./types";

const A = {
  tint: "#64D2FF",
  violet: "#A78BFA",
  mint: "#7CFFB2",
  amber: "#FFD37C",
  rose: "#FF7CEB",
  red: "#FF6B6B",
  slate: "#94A3B8",
  gold: "#F6C177",
  teal: "#2EE9A6",
};

const b = (x: BadgeDef) => x;

export const BADGES: BadgeDef[] = [
  // ───────── Consistency (streaks + comeback) ─────────
  b({
    id: "streak_1",
    title: "First Step",
    subtitle: "Logged something today",
    description: "You showed up. That’s the whole start.",
    criteriaText: "Log any meal, workout, or steps on 1 day.",
    category: "consistency",
    rarity: "common",
    icon: "sparkles",
    accent: A.tint,
    canFeature: true,
  }),
  b({
    id: "streak_3",
    title: "Back Again",
    subtitle: "3-day streak",
    description: "Quiet consistency. The kind that compounds.",
    criteriaText: "Log on 3 consecutive days.",
    category: "consistency",
    rarity: "common",
    icon: "flame",
    accent: A.rose,
    canFeature: true,
  }),
  b({
    id: "streak_7",
    title: "Settling In",
    subtitle: "7-day streak",
    description: "A week of proof you can trust yourself.",
    criteriaText: "Log on 7 consecutive days.",
    category: "consistency",
    rarity: "rare",
    icon: "flame",
    accent: A.violet,
    canFeature: true,
  }),
  b({
    id: "streak_14",
    title: "Ritual Builder",
    subtitle: "14-day streak",
    description: "It’s starting to feel normal. That’s the point.",
    criteriaText: "Log on 14 consecutive days.",
    category: "consistency",
    rarity: "rare",
    icon: "infinite",
    accent: A.mint,
    canFeature: true,
  }),
  b({
    id: "streak_30",
    title: "Unbroken",
    subtitle: "30-day streak",
    description: "A month of showing up — quietly impressive.",
    criteriaText: "Log on 30 consecutive days.",
    category: "consistency",
    rarity: "epic",
    icon: "trophy",
    accent: A.gold,
    canFeature: true,
  }),
  b({
    id: "comeback_1",
    title: "Still Showed Up",
    subtitle: "Returned after a miss",
    description: "The comeback is the habit.",
    criteriaText: "Log today after a break (streak reset).",
    category: "consistency",
    rarity: "common",
    icon: "refresh",
    accent: A.slate,
    hiddenUntilUnlocked: true,
  }),
  b({
    id: "comeback_3",
    title: "Reset Without Guilt",
    subtitle: "Started again, intentionally",
    description: "No drama. Just another rep of consistency.",
    criteriaText: "Start a new streak after losing one.",
    category: "consistency",
    rarity: "rare",
    icon: "leaf",
    accent: A.mint,
    hiddenUntilUnlocked: true,
  }),

  // ───────── Workouts / milestones ─────────
  b({
    id: "workout_1",
    title: "First Session",
    subtitle: "Workout logged",
    description: "The first entry is the hardest.",
    criteriaText: "Log 1 workout.",
    category: "milestones",
    rarity: "common",
    icon: "barbell",
    accent: A.tint,
    canFeature: true,
  }),
  b({
    id: "workout_3",
    title: "Warm-Up Complete",
    subtitle: "3 workouts total",
    description: "You’re building a pattern.",
    criteriaText: "Log 3 workouts.",
    category: "milestones",
    rarity: "common",
    icon: "barbell",
    accent: A.mint,
  }),
  b({
    id: "workout_10",
    title: "Getting Serious",
    subtitle: "10 workouts total",
    description: "Enough reps of the habit to feel it stick.",
    criteriaText: "Log 10 workouts.",
    category: "milestones",
    rarity: "rare",
    icon: "trophy",
    accent: A.violet,
    canFeature: true,
  }),
  b({
    id: "workout_25",
    title: "In the Routine",
    subtitle: "25 workouts total",
    description: "Quietly stacking sessions.",
    criteriaText: "Log 25 workouts.",
    category: "milestones",
    rarity: "rare",
    icon: "calendar",
    accent: A.rose,
  }),
  b({
    id: "workout_50",
    title: "Committed",
    subtitle: "50 workouts total",
    description: "This isn’t motivation anymore — it’s identity.",
    criteriaText: "Log 50 workouts.",
    category: "milestones",
    rarity: "epic",
    icon: "medal",
    accent: A.gold,
    canFeature: true,
  }),
  b({
    id: "workout_100",
    title: "Training Is Normal Now",
    subtitle: "100 workouts total",
    description: "A body of work. Literally.",
    criteriaText: "Log 100 workouts.",
    category: "milestones",
    rarity: "epic",
    icon: "ribbon",
    accent: A.gold,
    canFeature: true,
  }),

  // ───────── Workout streak (separate from overall logging streak) ─────────
  b({
    id: "wkstreak_3",
    title: "Three in a Row",
    subtitle: "Workout streak: 3",
    description: "Momentum, maintained.",
    criteriaText: "Log workouts on 3 consecutive days.",
    category: "strength",
    rarity: "common",
    icon: "flame",
    accent: A.rose,
  }),
  b({
    id: "wkstreak_7",
    title: "Weekly Rhythm",
    subtitle: "Workout streak: 7",
    description: "A week of training consistency.",
    criteriaText: "Log workouts on 7 consecutive days.",
    category: "strength",
    rarity: "rare",
    icon: "pulse",
    accent: A.violet,
    canFeature: true,
  }),
  b({
    id: "wkstreak_14",
    title: "Unshakable",
    subtitle: "Workout streak: 14",
    description: "Discipline with softness.",
    criteriaText: "Log workouts on 14 consecutive days.",
    category: "strength",
    rarity: "epic",
    icon: "shield-checkmark",
    accent: A.gold,
    canFeature: true,
  }),

  // ───────── Weekly training volume (sessions/week) ─────────
  b({
    id: "wk_2",
    title: "Two Sessions",
    subtitle: "This week",
    description: "You’re moving with intention.",
    criteriaText: "Log 2 workouts in a week.",
    category: "strength",
    rarity: "common",
    icon: "calendar",
    accent: A.tint,
  }),
  b({
    id: "wk_4",
    title: "Four Sessions",
    subtitle: "This week",
    description: "A strong week — quietly done.",
    criteriaText: "Log 4 workouts in a week.",
    category: "strength",
    rarity: "rare",
    icon: "calendar-number",
    accent: A.violet,
    canFeature: true,
  }),
  b({
    id: "wk_6",
    title: "Six Sessions",
    subtitle: "This week",
    description: "High consistency. Respect the recovery too.",
    criteriaText: "Log 6 workouts in a week.",
    category: "strength",
    rarity: "epic",
    icon: "thunderstorm",
    accent: A.gold,
    canFeature: true,
  }),

  // ───────── Steps / movement ─────────
  b({
    id: "steps_any",
    title: "Moved Today",
    subtitle: "Steps logged",
    description: "Motion counts, even the quiet kind.",
    criteriaText: "Log steps today (any amount).",
    category: "habits",
    rarity: "common",
    icon: "walk",
    accent: A.mint,
  }),
  b({
    id: "steps_5k",
    title: "5k Club",
    subtitle: "5,000 steps today",
    description: "A solid baseline day.",
    criteriaText: "Reach 5,000 steps in a day.",
    category: "habits",
    rarity: "common",
    icon: "footsteps",
    accent: A.tint,
  }),
  b({
    id: "steps_10k",
    title: "10k Day",
    subtitle: "10,000 steps today",
    description: "Classic. Still earned.",
    criteriaText: "Reach 10,000 steps in a day.",
    category: "habits",
    rarity: "rare",
    icon: "walk",
    accent: A.violet,
    canFeature: true,
  }),
  b({
    id: "steps_10k_3w",
    title: "Walker’s Rhythm",
    subtitle: "3× 10k this week",
    description: "You found a pace you can repeat.",
    criteriaText: "Hit 10k steps on 3 days in a week.",
    category: "habits",
    rarity: "rare",
    icon: "trail-sign",
    accent: A.mint,
  }),
  b({
    id: "steps_10k_7w",
    title: "Daily Motion",
    subtitle: "7× 10k this week",
    description: "A week of movement you can feel.",
    criteriaText: "Hit 10k steps on 7 days in a week.",
    category: "habits",
    rarity: "epic",
    icon: "planet",
    accent: A.gold,
    canFeature: true,
  }),

  // ───────── Nutrition logging / structure ─────────
  b({
    id: "meal_1",
    title: "First Bite",
    subtitle: "Meal logged",
    description: "Awareness is the first upgrade.",
    criteriaText: "Log 1 meal.",
    category: "nutrition",
    rarity: "common",
    icon: "nutrition",
    accent: A.tint,
    canFeature: true,
  }),
  b({
    id: "meal_10",
    title: "No Guessing",
    subtitle: "10 meals logged",
    description: "Data beats vibes — gently.",
    criteriaText: "Log 10 meals.",
    category: "nutrition",
    rarity: "common",
    icon: "list",
    accent: A.mint,
  }),
  b({
    id: "meal_50",
    title: "Macro Minded",
    subtitle: "50 meals logged",
    description: "You’re building awareness with reps.",
    criteriaText: "Log 50 meals.",
    category: "nutrition",
    rarity: "rare",
    icon: "analytics",
    accent: A.violet,
    canFeature: true,
  }),
  b({
    id: "meal_150",
    title: "Fuel Archivist",
    subtitle: "150 meals logged",
    description: "You’ve built a real record of your habits.",
    criteriaText: "Log 150 meals.",
    category: "nutrition",
    rarity: "epic",
    icon: "library",
    accent: A.gold,
    canFeature: true,
  }),

  // ───────── Protein / fiber weekly “wins” ─────────
  b({
    id: "protein_3w",
    title: "Protein, Mostly",
    subtitle: "3 days this week",
    description: "Not perfect. Consistent enough.",
    criteriaText: "Hit protein target on 3 days this week.",
    category: "nutrition",
    rarity: "common",
    icon: "flash",
    accent: A.mint,
  }),
  b({
    id: "protein_5w",
    title: "Built on Protein",
    subtitle: "5 days this week",
    description: "The boring basics — done well.",
    criteriaText: "Hit protein target on 5 days this week.",
    category: "nutrition",
    rarity: "rare",
    icon: "flash",
    accent: A.violet,
    canFeature: true,
  }),
  b({
    id: "protein_7w",
    title: "Protein Is Automatic",
    subtitle: "7 days this week",
    description: "Dialed.",
    criteriaText: "Hit protein target on 7 days this week.",
    category: "nutrition",
    rarity: "epic",
    icon: "checkmark-done",
    accent: A.gold,
    canFeature: true,
  }),
  b({
    id: "fiber_3w",
    title: "Fiber Aware",
    subtitle: "3 days this week",
    description: "Your future self thanks you.",
    criteriaText: "Hit fiber goal on 3 days this week.",
    category: "recovery",
    rarity: "common",
    icon: "leaf",
    accent: A.mint,
  }),
  b({
    id: "fiber_5w",
    title: "Digestive Peace",
    subtitle: "5 days this week",
    description: "Quiet recovery you can feel.",
    criteriaText: "Hit fiber goal on 5 days this week.",
    category: "recovery",
    rarity: "rare",
    icon: "leaf",
    accent: A.violet,
  }),
  b({
    id: "fiber_7w",
    title: "Gut Calm",
    subtitle: "7 days this week",
    description: "Consistency — inside and out.",
    criteriaText: "Hit fiber goal on 7 days this week.",
    category: "recovery",
    rarity: "epic",
    icon: "heart",
    accent: A.gold,
    canFeature: true,
  }),

  // ───────── “Invisible identity” badges (hidden) ─────────
  b({
    id: "identity_morning",
    title: "Morning Trainer",
    subtitle: "A pattern emerged",
    description: "You tend to train early. It suits you.",
    criteriaText: "Log most workouts before noon (over time).",
    category: "habits",
    rarity: "rare",
    icon: "sunny",
    accent: A.amber,
    hiddenUntilUnlocked: true,
  }),
  b({
    id: "identity_night",
    title: "Late-Night Grinder",
    subtitle: "A pattern emerged",
    description: "You get it done when it’s quiet.",
    criteriaText: "Log most workouts after 8pm (over time).",
    category: "habits",
    rarity: "rare",
    icon: "moon",
    accent: A.violet,
    hiddenUntilUnlocked: true,
  }),
  b({
    id: "identity_weekday",
    title: "Weekday Warrior",
    subtitle: "Consistency where it counts",
    description: "You show up during the week — life and all.",
    criteriaText: "Log workouts mostly Mon–Fri (over time).",
    category: "habits",
    rarity: "rare",
    icon: "briefcase",
    accent: A.slate,
    hiddenUntilUnlocked: true,
  }),

  // ───────── Premium / meta ─────────
  b({
    id: "premium_member",
    title: "Premium Supporter",
    subtitle: "Thank you",
    description: "You’re directly supporting thoughtful product design.",
    criteriaText: "Unlock by having Premium active.",
    category: "premium",
    rarity: "rare",
    icon: "star",
    accent: A.gold,
    canFeature: true,
  }),
  b({
    id: "quick_session_finish",
    title: "Efficient",
    subtitle: "12+ sets in a session",
    description: "Quiet intensity. No wasted reps.",
    criteriaText: "Log a workout with 12+ sets.",
    category: "strength",
    rarity: "common",
    icon: "timer",
    accent: "#7CFFB2",
  }),
  b({
    id: "protein_strike",
    title: "Protein Hit",
    subtitle: "40g+ in one meal",
    description: "A clean, satisfying anchor.",
    criteriaText: "Log a meal with 40g+ protein.",
    category: "nutrition",
    rarity: "common",
    icon: "flash",
    accent: "#64D2FF",
  }),
  b({
    id: "steps_boost",
    title: "Small Add, Big Win",
    subtitle: "+2,000 steps",
    description: "A little walk changes the day.",
    criteriaText: "Add/set 2,000+ steps at once.",
    category: "habits",
    rarity: "common",
    icon: "walk",
    accent: "#A78BFA",
  }),

  // ───────── Extra “micro-rewards” (lots of them; keep common) ─────────
  // These are intentionally lightweight so users feel rewarded often.
  ...[
    [
      "log_2w",
      "Quiet Week",
      "Logged 2 days this week",
      "Log on 2 days in a week.",
      "calendar-outline",
      A.tint,
    ],
    [
      "log_4w",
      "Steady Week",
      "Logged 4 days this week",
      "Log on 4 days in a week.",
      "calendar",
      A.mint,
    ],
    [
      "log_6w",
      "Nearly Daily",
      "Logged 6 days this week",
      "Log on 6 days in a week.",
      "calendar-number",
      A.violet,
    ],
    [
      "steps_12k",
      "12k Drift",
      "12,000 steps today",
      "Reach 12,000 steps in a day.",
      "walk-outline",
      A.mint,
    ],
    [
      "steps_15k",
      "15k Day",
      "15,000 steps today",
      "Reach 15,000 steps in a day.",
      "trail-sign-outline",
      A.violet,
    ],
    [
      "wk_1",
      "Quick Session",
      "1 workout this week",
      "Log 1 workout in a week.",
      "barbell-outline",
      A.tint,
    ],
    [
      "wk_3",
      "Three Sessions",
      "3 workouts this week",
      "Log 3 workouts in a week.",
      "barbell",
      A.mint,
    ],
    [
      "meal_25",
      "Food Aware",
      "25 meals logged",
      "Log 25 meals.",
      "nutrition-outline",
      A.tint,
    ],
    [
      "meal_75",
      "Fuel Notes",
      "75 meals logged",
      "Log 75 meals.",
      "document-text",
      A.mint,
    ],
    [
      "meal_300",
      "Long Memory",
      "300 meals logged",
      "Log 300 meals.",
      "time",
      A.gold,
    ],
  ].map(([id, title, subtitle, criteriaText, icon, accent]) =>
    b({
      id: String(id),
      title: String(title),
      subtitle: String(subtitle),
      description: "A small win. Not loud. Still real.",
      criteriaText: String(criteriaText),
      category: id.startsWith("meal")
        ? "nutrition"
        : id.startsWith("steps")
        ? "habits"
        : "consistency",
      rarity: id.endsWith("300")
        ? "epic"
        : id.endsWith("6w")
        ? "rare"
        : "common",
      icon: String(icon),
      accent: String(accent),
    })
  ),

  // You can keep adding here over time without breaking anything.
];

export const BADGE_BY_ID: Record<string, BadgeDef> = Object.fromEntries(
  BADGES.map((x) => [x.id, x])
);
